line_arbiter_prefix: "PMPS:KFE:"
undulator_kicker_rate_pv: "IOC:BSY0:MP01:BYKIKS_RATE"
accelerator_mode_pv: "SIOC:FEES:MP01:FACMODE_RBV"
trans_req_pv: "AT1K0:GAS:TRANS_REQ_RBV"
trans_rbv_pv: "AT1K0:GAS:TRANS_RBV"

dashboard_url: "http://ctl-logsrv01:3000/ctl/grafana/d/PRr2cuGGz/k-pmps-events?viewPanel=2&orgId=1&refresh=10s&kiosk"

fastfaults:
  - name: "KFE Arbiter"
    prefix: "PMPS:KFE:"
    ffo_desc: ["PMPS System", "PMPS System","TMO OPTICS COMM.","TMO VAC,MOT COMM.", "RIX VAC, MOT COMM","QRIX,CRIX COMM.", "TXI VAC,MOT COMM." ]
    ffo_veto: ["None", "None","MR1K1_IN","ST3K4_IN","MR1K1_OUT", "MR1K1_OUT OR ST1K2_IN","MR1K3_OUT AND MR2K3_OUT" ]
    ffo_start: 1
    ffo_end: 7
    ff_start: 1
    ff_end: 50

  - name: "KFE GATT"
    prefix: "PLC:KFE:GATT:"
    ffo_desc: ["All KFE GATT", "Spare"]
    ffo_veto: ["None", "None"]
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 75

  - name: "KFE Vacuum"
    prefix: "PLC:KFE:VAC:K0:"
    ffo_desc:
      - "K0 Upstream"
      - "K1 Mirrors"
      - "K2/RIX"
      - "K3/TXI"
      - "K4/TMO upstream ST3K4"
      - "K0 Fast Shutters"
    ffo_veto:
      - "None"
      - "ST1K0 IN"
      - "MR1K1 OUT or ST1K0 IN"
      - "MR1K1 IN or MR1K3 OUT or ST1K0 IN"
      - "MR1K1 IN or MR1K3 IN or ST1K0 IN"
      - "None"
    ffo_start: 1
    ffo_end: 6
    ff_start: 1
    ff_end: 20

  - name: "TMO Vacuum"
    prefix: "PLC:TMO:VAC:"
    ffo_desc:
      - "Spare"
      - "From ST3K4 to ST4K4"
      - "Spare"
      - "US Mirror Fast Shutters"
      - "Downstream of ST4K4"
      - "DS Mirror Fast Shutters"
    ffo_veto:
      - "Always"
      - "MR1K1, MR1K3, ST1K0, ST3K4"
      - "N/a"
      - "MR1K1, MR1K3, ST1K0, ST3K4"
      - "MR1K1, MR1L3, ST1K0, ST3K4, ST4K4"
      - "MR1K1, MR1K3, ST1K0, ST3K4, ST4K4"
    ffo_start: 1
    ffo_end: 6
    ff_start: 1
    ff_end: 50

  - name: "TMO Optics"
    prefix: "PLC:TMO:OPTICS:"
    ffo_desc: ["Upstream of ST3K4", "Downstream of ST3K4", "Downstream of ST4K4"]
    ffo_veto: ["ST1K0, MR1K1", "ST1K0, MR1K1, ST3K4", "ST1K0, MR1K1, ST3K4, ST4K4"]
    ffo_start: 1
    ffo_end: 3
    ff_start: 1
    ff_end: 70

  - name: "TMO CC Motion"
    prefix: "PLC:TMO:MOTION:"
    ffo_desc: ["Upstream of ST4K4", "Downstream of ST4K4"]
    ffo_veto: ["MR1K1, ST1K0, ST3K4", "MR1K1, ST1K0, ST3K4, ST4K4"]
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 200

  - name: "KFE CC Motion"
    prefix: "PLC:KFE:MOTION:"
    ffo_desc: ["Upstream of ST1K0", "TMO line after MR1K1", "TXI line after MR1K3", "Between ST1K0 and MR1K1"]
    ffo_veto: ["None", "ST1K0, MR1K1, or MR1K3 IN", "ST1K0 IN, MR1K1 IN, or MR1K3 OUT", "ST1K0 IN"]
    ffo_start: 1
    ffo_end: 4
    ff_start: 1
    ff_end: 50

  - name: "RIX Optics"
    prefix: "PLC:RIX:OPTICS:"
    ffo_desc: ["Upstream of ST1K2", "Downstream of ST1K2"]
    ffo_veto: ["MR1K1 OUT or ST1K0 IN", "MR1K1 OUT or ST1K0 IN or ST1K2 IN"]
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 65

  - name: "RIX Vacuum"
    prefix: "PLC:KFE:RIX:VAC:K2:"
    ffo_desc: ["Upstream of ST1K2", "Downstream of ST1K2"]
    ffo_veto: ["MR1K1 OUT or ST1K0 IN", "MR1K1 OUT or ST1K0 IN or ST1K2 IN"]
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 50

  - name: "RIX CC Motion"
    prefix: "PLC:RIX:MOTION:"
    ffo_desc: ["Upstream of ST1K2", "Downstream of ST1K2"]
    ffo_veto: ["MR1K1 OUT or ST1K0 IN", "MR1K1 OUT or ST1K0 IN or ST1K2 IN"]
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 230

  - name: "CRIX Vacuum"
    prefix: "PLC:CRIXS:VAC:"
    ffo_desc: ["All CRIX Vac", "Spare"]
    ffo_veto: ["MR1K1 OUT or ST1K0 IN or ST1K2 IN", "MR1K1 OUT or ST1K0 IN or ST1K2 IN"]
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 50

  - name: "CRIX Motion"
    prefix: "PLC:CRIX:MOT:"
    ffo_desc: ["Spare", "Spare"]
    ffo_veto: ["MR1K1 OUT or ST1K0 IN or ST1K2 IN", "MR1K1 OUT or ST1K0 IN or ST1K2 IN"]
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 50

  - name: "QRIX Vacuum"
    prefix: "PLC:QRIX:VAC:"
    ffo_desc: ["QRIX Beamline Valves", "Spare"]
    ffo_veto: ["MR1K1 OUT or ST1K2 IN", "MR1K1 OUT or ST1K2 IN"]
    ffo_start: 1
    ffo_end: 1
    ff_start: 1
    ff_end: 50

  - name: "TXI K  Vacuum"
    prefix: "PLC:TXI:VAC:"
    ffo_desc: ["TXI K3 Beamline Valves", "Spare"]
    ffo_veto: ["MR1K3 OUT or ST1K3 IN", "MR1K3 OUT or ST1K3 IN"]
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 50

  - name: "TXI K3 motion"
    prefix: "PLC:TXI:SXR:MOTION:"
    ffo_desc: ["TXI K3 Beamline Diagnostics", "Spare"]
    ffo_veto: ["MR1K3 OUT or ST1K3 IN", "MR1K3 OUT or ST1K3 IN"]
    ffo_start: 1
    ffo_end: 1
    ff_start: 1
    ff_end: 50

  - name: "TXI K Optics"
    prefix: "PLC:TXI:KFE:OPTICS:"
    ffo_desc: ["TXI K3 Beamline OPTICS", "Spare"]
    ffo_veto: ["MR1K1 IN", "MR1K1 IN"]
    ffo_start: 1
    ffo_end: 1
    ff_start: 1
    ff_end: 50


preemptive_requests:
  - prefix: "PMPS:KFE:"
    arbiter_instance: "Arbiter:02"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PMPS:KFE:"
    arbiter_instance: "Arbiter:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:KFE:MOTION:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:KFE:MOTION:"
    arbiter_instance: "ARB:02"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:KFE:MOTION:"
    arbiter_instance: "ARB:03"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:KFE:MOTION:"
    arbiter_instance: "ARB:04"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:KFE:VAC:K0:"
    arbiter_instance: "Arb:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:KFE:GATT:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:KFE:GATT:"
    arbiter_instance: "ARB:02"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:TMO:OPTICS:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:TMO:OPTICS:"
    arbiter_instance: "ARB:02"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:TMO:MOTION:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 30

  - prefix: "PLC:TMO:MOTION:"
    arbiter_instance: "ARB:02"
    assertion_pool_start: 1
    assertion_pool_end: 30

  - prefix: "PLC:TMO:VAC:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:TMO:VAC:"
    arbiter_instance: "ARB:02"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:RIX:OPTICS:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:RIX:OPTICS:"
    arbiter_instance: "ARB:02"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:RIX:MOTION:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 50

  - prefix: "PLC:RIX:MOTION:"
    arbiter_instance: "ARB:02"
    assertion_pool_start: 1
    assertion_pool_end: 50

  - prefix: "PLC:KFE:RIX:VAC:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:KFE:RIX:VAC:"
    arbiter_instance: "ARB:02"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:CRIXS:VAC:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:CRIX:MOT:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:QRIX:VAC:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:TXI:VAC:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:TXI:SXR:MOTION:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:TXI:KFE:OPTICS:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20
